[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://trenton.netlify.app/*"
  to = "http://trenton.taistudio.fr/:splat"
  status = 301
  force = true
